jam: Fix build warning. Add missing include for Linux.
Warning was:

Cc bin.linuxx86/execunix.o
execunix.c: In function ‘execwait’:
execunix.c:301:19: warning: implicit declaration of function ‘wait’ [-Wimplicit-function-declaration]
  301 |      while( ( w = wait( &status ) ) == -1 && errno == EINTR )
      |

Change-Id: I7c0e53db8d18e9e6cb317980cb9be9026b7fce20
Reviewed-on: https://review.haiku-os.org/c/buildtools/+/4400
Reviewed-by: Jérôme Duval <jerome.duval@gmail.com>